### ISSUE TITLE
Wrong winner of best pitch.

### ISSUE THREAD

**Issue by miniskurken** [OpenHackC4H/OpenhackC4H#1]
I think you have mixed up the actual winner of the best pitch category, Shotgun Sorters won best pitch.

**Comment by johanlinaker** [comment]
Hej! Enligt Shotgun Shooters/Skillset Recruitments presentation tolkade jag det som att lösningen heter WithRefugees. Jag kan såklart ändra om detta är felaktigt. /Johan

**Comment by miniskurken** [comment]
Då har du nog tolkat lite fel :) ta i för att du ändrar :-)

**Comment by miniskurken** [comment]
Tack för att du ändrar :)

**Comment by johanlinaker** [comment]
Uppdaterat!
